package Calculator;


/**
* Calculator/CalculatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Segunda-feira, 24 de Abril de 2023 20h54min14s BRT
*/

public interface CalculatorInterface extends CalculatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculatorInterface
