package Calculator;


/**
* Calculator/CalculatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Segunda-feira, 24 de Abril de 2023 20h54min14s BRT
*/

public interface CalculatorInterfaceOperations 
{
  float add (float num1, float num2);
  float subtract (float num1, float num2);
  float multiply (float num1, float num2);
  float divide (float num1, float num2);
} // interface CalculatorInterfaceOperations
